// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type HealthStatusError struct {
	Role      *components.Role        `json:"role,omitempty"`
	Status    components.Status       `json:"status"`
	StartTime float64                 `json:"startTime"`
	HTTPMeta  components.HTTPMetadata `json:"-"`
}

var _ error = &HealthStatusError{}

func (e *HealthStatusError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
