/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { diagGetHealthInfo } from "../../funcs/diagGetHealthInfo.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$diagGetHealthInfo: ToolDefinition = {
  name: "diag-get-health-info",
  description: `Provides health info for REST server`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await diagGetHealthInfo(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
