/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { CriblControlPlane } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Diag Get Health Info", async () => {
  const testHttpClient = createTestHTTPClient("getHealthInfo");

  const criblControlPlane = new CriblControlPlane({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await criblControlPlane.diag.getHealthInfo();
  expect(result).toBeDefined();
  expect(result).toEqual({
    status: "standby",
    startTime: 8399.98,
  });
});
