/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { diagGetHealthInfo } from "../funcs/diagGetHealthInfo.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Diag extends ClientSDK {
  /**
   * Provides health info for REST server
   */
  async getHealthInfo(
    options?: RequestOptions,
  ): Promise<models.HealthStatus> {
    return unwrapAsync(diagGetHealthInfo(
      this,
      options,
    ));
  }
}
