// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetHealthInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Healthy status
	HealthStatus *components.HealthStatus
}

func (o *GetHealthInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetHealthInfoResponse) GetHealthStatus() *components.HealthStatus {
	if o == nil {
		return nil
	}
	return o.HealthStatus
}
