/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the cribl-control-plane SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx diagGetHealthInfo.ts
 */

import { CriblControlPlane } from "cribl-control-plane";

const criblControlPlane = new CriblControlPlane({
  serverURL: "https://api.example.com",
});

async function main() {
  const result = await criblControlPlane.getHealthInfo();

  console.log(result);
}

main().catch(console.error);
