// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Role string

const (
	RolePrimary Role = "primary"
	RoleStandby Role = "standby"
)

func (e Role) ToPointer() *Role {
	return &e
}

type Status string

const (
	StatusHealthy      Status = "healthy"
	StatusShuttingDown Status = "shutting down"
	StatusStandby      Status = "standby"
)

func (e Status) ToPointer() *Status {
	return &e
}

type HealthStatus struct {
	Role      *Role   `json:"role,omitempty"`
	Status    Status  `json:"status"`
	StartTime float64 `json:"startTime"`
}

func (o *HealthStatus) GetRole() *Role {
	if o == nil {
		return nil
	}
	return o.Role
}

func (o *HealthStatus) GetStatus() Status {
	if o == nil {
		return Status("")
	}
	return o.Status
}

func (o *HealthStatus) GetStartTime() float64 {
	if o == nil {
		return 0.0
	}
	return o.StartTime
}
