// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	BearerAuth  *string            `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	ClientOauth *SchemeClientOauth `security:"scheme,type=oauth2,subtype=client_credentials"`
}

func (o *Security) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *Security) GetClientOauth() *SchemeClientOauth {
	if o == nil {
		return nil
	}
	return o.ClientOauth
}
