/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Role = {
  Primary: "primary",
  Standby: "standby",
} as const;
export type Role = OpenEnum<typeof Role>;

export const Status = {
  Healthy: "healthy",
  ShuttingDown: "shutting down",
  Standby: "standby",
} as const;
export type Status = OpenEnum<typeof Status>;

export type HealthStatus = {
  role?: Role | undefined;
  status: Status;
  startTime: number;
};

/** @internal */
export const Role$inboundSchema: z.ZodType<Role, z.ZodTypeDef, unknown> = z
  .union([
    z.nativeEnum(Role),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const Role$outboundSchema: z.ZodType<Role, z.ZodTypeDef, Role> = z.union(
  [
    z.nativeEnum(Role),
    z.string().and(z.custom<Unrecognized<string>>()),
  ],
);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Role$ {
  /** @deprecated use `Role$inboundSchema` instead. */
  export const inboundSchema = Role$inboundSchema;
  /** @deprecated use `Role$outboundSchema` instead. */
  export const outboundSchema = Role$outboundSchema;
}

/** @internal */
export const Status$inboundSchema: z.ZodType<Status, z.ZodTypeDef, unknown> = z
  .union([
    z.nativeEnum(Status),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const Status$outboundSchema: z.ZodType<Status, z.ZodTypeDef, Status> = z
  .union([
    z.nativeEnum(Status),
    z.string().and(z.custom<Unrecognized<string>>()),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const HealthStatus$inboundSchema: z.ZodType<
  HealthStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  role: Role$inboundSchema.optional(),
  status: Status$inboundSchema,
  startTime: z.number(),
});

/** @internal */
export type HealthStatus$Outbound = {
  role?: string | undefined;
  status: string;
  startTime: number;
};

/** @internal */
export const HealthStatus$outboundSchema: z.ZodType<
  HealthStatus$Outbound,
  z.ZodTypeDef,
  HealthStatus
> = z.object({
  role: Role$outboundSchema.optional(),
  status: Status$outboundSchema,
  startTime: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HealthStatus$ {
  /** @deprecated use `HealthStatus$inboundSchema` instead. */
  export const inboundSchema = HealthStatus$inboundSchema;
  /** @deprecated use `HealthStatus$outboundSchema` instead. */
  export const outboundSchema = HealthStatus$outboundSchema;
  /** @deprecated use `HealthStatus$Outbound` instead. */
  export type Outbound = HealthStatus$Outbound;
}

export function healthStatusToJSON(healthStatus: HealthStatus): string {
  return JSON.stringify(HealthStatus$outboundSchema.parse(healthStatus));
}

export function healthStatusFromJSON(
  jsonString: string,
): SafeParseResult<HealthStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HealthStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HealthStatus' from JSON`,
  );
}
