/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SchemeClientOauth = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

/** @internal */
export const SchemeClientOauth$inboundSchema: z.ZodType<
  SchemeClientOauth,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://login.cribl.cloud/oauth/token"),
});

/** @internal */
export type SchemeClientOauth$Outbound = {
  clientID: string;
  clientSecret: string;
  tokenURL: string;
};

/** @internal */
export const SchemeClientOauth$outboundSchema: z.ZodType<
  SchemeClientOauth$Outbound,
  z.ZodTypeDef,
  SchemeClientOauth
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://login.cribl.cloud/oauth/token"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SchemeClientOauth$ {
  /** @deprecated use `SchemeClientOauth$inboundSchema` instead. */
  export const inboundSchema = SchemeClientOauth$inboundSchema;
  /** @deprecated use `SchemeClientOauth$outboundSchema` instead. */
  export const outboundSchema = SchemeClientOauth$outboundSchema;
  /** @deprecated use `SchemeClientOauth$Outbound` instead. */
  export type Outbound = SchemeClientOauth$Outbound;
}

export function schemeClientOauthToJSON(
  schemeClientOauth: SchemeClientOauth,
): string {
  return JSON.stringify(
    SchemeClientOauth$outboundSchema.parse(schemeClientOauth),
  );
}

export function schemeClientOauthFromJSON(
  jsonString: string,
): SafeParseResult<SchemeClientOauth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemeClientOauth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemeClientOauth' from JSON`,
  );
}
